src/Entity/Clases.php
<?php

namespace App\Entity;

use App\Repository\ClasesRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ClasesRepository::class)]
class Clases
{


    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 200)]
    private ?string $Nombre = null;

    #[ORM\Column(length: 2000)]
    private ?string $Requisitos = null;

    #[ORM\Column(length: 999)]
    private ?string $Competencias = null;

    #[ORM\Column(length: 999)]
    private ?string $Salvaciones = null;

    #[ORM\Column(length: 999)]
    private ?string $HabilidadesAElegir = null;

    #[ORM\Column(length: 100)]
    private ?string $PuntosDeGolpe = null;

    #[ORM\Column(length: 999)]
    private ?string $Equipamiento = null;

    #[ORM\Column(length: 350)]
    private ?string $Autor = null;

    #[ORM\Column]
    private ?bool $Validado = null;

    #[ORM\Column(length: 2000, nullable: true)]
    private ?string $img = null;

    #[ORM\Column]
    private ?int $Magia = null;

    #[ORM\Column(length: 255)]
    private ?string $ipAddress = null;

    #[ORM\Column(type: "datetime", nullable: true)]
    private ?\DateTimeInterface $createdAt = null;

    public function __construct()
    {
        $this->createdAt = new \DateTime();
    }

    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->Nombre;
    }

    public function setNombre(string $Nombre): static
    {
        $this->Nombre = $Nombre;

        return $this;
    }

    public function getRequisitos(): ?string
    {
        return $this->Requisitos;
    }

    public function setRequisitos(string $Requisitos): static
    {
        $this->Requisitos = $Requisitos;

        return $this;
    }

    public function getCompetencias(): ?string
    {
        return $this->Competencias;
    }

    public function setCompetencias(string $Competencias): static
    {
        $this->Competencias = $Competencias;

        return $this;
    }

    public function getSalvaciones(): ?string
    {
        return $this->Salvaciones;
    }

    public function setSalvaciones(string $Salvaciones): static
    {
        $this->Salvaciones = $Salvaciones;

        return $this;
    }

    public function getHabilidadesAElegir(): ?string
    {
        return $this->HabilidadesAElegir;
    }

    public function setHabilidadesAElegir(string $HabilidadesAElegir): static
    {
        $this->HabilidadesAElegir = $HabilidadesAElegir;

        return $this;
    }

    public function getPuntosDeGolpe(): ?string
    {
        return $this->PuntosDeGolpe;
    }

    public function setPuntosDeGolpe(string $PuntosDeGolpe): static
    {
        $this->PuntosDeGolpe = $PuntosDeGolpe;

        return $this;
    }

    public function getEquipamiento(): ?string
    {
        return $this->Equipamiento;
    }

    public function setEquipamiento(string $equipamiento): static
    {
        $this->Equipamiento = $equipamiento;

        return $this;
    }

    public function getAutor(): ?string
    {
        return $this->Autor;
    }

    public function setAutor(string $Autor): static
    {
        $this->Autor = $Autor;

        return $this;
    }

    public function isValidado(): ?bool
    {
        return $this->Validado;
    }

    public function setValidado(bool $Validado): static
    {
        $this->Validado = $Validado;

        return $this;
    }

    public function getImg(): ?string
    {
        return $this->img;
    }

    public function setImg(string $img): static
    {
        $this->img = $img;

        return $this;
    }

    public function getMagia(): ?int
    {
        return $this->Magia;
    }

    public function setMagia(int $Magia): static
    {
        $this->Magia = $Magia;

        return $this;
    }

    public function getIpAddress(): ?string
    {
        return $this->ipAddress;
    }

    public function setIpAddress(string $ipAddress): static
    {
        $this->ipAddress = $ipAddress;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(?\DateTimeInterface $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

   

    
}

src/Entity/Dotes.php
<?php

namespace App\Entity;

use App\Repository\DotesRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: DotesRepository::class)]
class Dotes
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $Nombre = null;

    #[ORM\Column(length: 999)]
    private ?string $Descripcion = null;

    #[ORM\Column(length: 100, nullable:true)]
    private ?string $Requisitos = null;

    #[ORM\Column(length: 200, nullable: true)]
    private ?string $Beneficios = null;

    #[ORM\Column]
    private ?bool $Validado = null;

    #[ORM\Column(length: 150)]
    private ?string $Autor = null;

    #[ORM\Column(length: 999)]
    private ?string $img = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->Nombre;
    }

    public function setNombre(string $Nombre): static
    {
        $this->Nombre = $Nombre;

        return $this;
    }

    public function getDescripcion(): ?string
    {
        return $this->Descripcion;
    }

    public function setDescripcion(string $Descripción): static
    {
        $this->Descripcion = $Descripción;

        return $this;
    }

    public function getRequisitos(): ?string
    {
        return $this->Requisitos;
    }

    public function setRequisitos(string $Requisitos): static
    {
        $this->Requisitos = $Requisitos;

        return $this;
    }

    public function getBeneficios(): ?string
    {
        return $this->Beneficios;
    }

    public function setBeneficios(?string $Beneficios): static
    {
        $this->Beneficios = $Beneficios;

        return $this;
    }

    public function isValidado(): ?bool
    {
        return $this->Validado;
    }

    public function setValidado(bool $Validado): static
    {
        $this->Validado = $Validado;

        return $this;
    }

    public function getAutor(): ?string
    {
        return $this->Autor;
    }

    public function setAutor(string $Autor): static
    {
        $this->Autor = $Autor;

        return $this;
    }

    public function getImg(): ?string
    {
        return $this->img;
    }

    public function setImg(string $img): static
    {
        $this->img = $img;

        return $this;
    }
}

src/Entity/Razas.php
<?php

namespace App\Entity;

use App\Repository\RazasRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RazasRepository::class)]
class Razas
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 200)]
    private ?string $Nombre = null;

    #[ORM\Column(length: 999)]
    private ?string $Descripcion = null;

    #[ORM\Column(length: 2)]
    private ?string $Fuerza = null;

    #[ORM\Column(length: 2)]
    private ?string $Destreza = null;

    #[ORM\Column(length: 2)]
    private ?string $Constitucion = null;

    #[ORM\Column(length: 2)]
    private ?string $Inteligencia = null;

    #[ORM\Column(length: 2)]
    private ?string $Sabiduria = null;

    #[ORM\Column(length: 2)]
    private ?string $Carisma = null;

    #[ORM\Column(length: 200)]
    private ?string $Autor = null;

    #[ORM\Column]
    private ?int $Velocidad = null;

    #[ORM\Column(length: 999)]
    private ?string $AtaqueDesarmado = null;

    #[ORM\Column]
    private ?bool $Validado = null;

    #[ORM\Column(length: 999)]
    private ?string $img = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->Nombre;
    }

    public function setNombre(string $Nombre): static
    {
        $this->Nombre = $Nombre;

        return $this;
    }

    public function getDescripcion(): ?string
    {
        return $this->Descripcion;
    }

    public function setDescripcion(string $Descripción): static
    {
        $this->Descripcion = $Descripción;

        return $this;
    }

    public function getFuerza(): ?string
    {
        return $this->Fuerza;
    }

    public function setFuerza(string $Fuerza): static
    {
        $this->Fuerza = $Fuerza;

        return $this;
    }

    public function getDestreza(): ?string
    {
        return $this->Destreza;
    }

    public function setDestreza(string $Destreza): static
    {
        $this->Destreza = $Destreza;

        return $this;
    }

    public function getConstitucion(): ?string
    {
        return $this->Constitucion;
    }

    public function setConstitucion(string $Constitucion): static
    {
        $this->Constitucion = $Constitucion;

        return $this;
    }

    public function getInteligencia(): ?string
    {
        return $this->Inteligencia;
    }

    public function setInteligencia(string $Inteligencia): static
    {
        $this->Inteligencia = $Inteligencia;

        return $this;
    }

    public function getSabiduria(): ?string
    {
        return $this->Sabiduria;
    }

    public function setSabiduria(string $Sabiduria): static
    {
        $this->Sabiduria = $Sabiduria;

        return $this;
    }

    public function getCarisma(): ?string
    {
        return $this->Carisma;
    }

    public function setCarisma(string $Carisma): static
    {
        $this->Carisma = $Carisma;

        return $this;
    }

    public function getAutor(): ?string
    {
        return $this->Autor;
    }

    public function setAutor(string $Autor): static
    {
        $this->Autor = $Autor;

        return $this;
    }

    public function getVelocidad(): ?int
    {
        return $this->Velocidad;
    }

    public function setVelocidad(int $Velocidad): static
    {
        $this->Velocidad = $Velocidad;

        return $this;
    }

    public function getAtaqueDesarmado(): ?string
    {
        return $this->AtaqueDesarmado;
    }

    public function setAtaqueDesarmado(string $AtaqueDesarmado): static
    {
        $this->AtaqueDesarmado = $AtaqueDesarmado;

        return $this;
    }

    public function isValidado(): ?bool
    {
        return $this->Validado;
    }

    public function setValidado(bool $Validado): static
    {
        $this->Validado = $Validado;

        return $this;
    }

    public function getImg(): ?string
    {
        return $this->img;
    }

    public function setImg(string $img): static
    {
        $this->img = $img;

        return $this;
    }
}

src/Entity/Trasfondo.php
<?php

namespace App\Entity;

use App\Repository\TrasfondoRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TrasfondoRepository::class)]
class Trasfondo
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 200)]
    private ?string $Nombre = null;

    #[ORM\Column(length: 999)]
    private ?string $Descripcion = null;

    #[ORM\Column(length:100)]
    private ?string $Origen = null;

    #[ORM\Column(length: 999, nullable: true)]
    private ?string $Idiomas = null;

    #[ORM\Column(length: 999, nullable: true)]
    private ?string $ObjetosIniciales = null;

    #[ORM\Column(length: 999, nullable: true)]
    private ?string $Competencias = null;

    #[ORM\Column]
    private ?bool $Validado = null;

    #[ORM\Column(length: 200)]
    private ?string $Autor = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $Plano = null;

    #[ORM\Column(length: 999)]
    private ?string $img = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->Nombre;
    }

    public function setNombre(string $Nombre): static
    {
        $this->Nombre = $Nombre;

        return $this;
    }

    public function getDescripcion(): ?string
    {
        return $this->Descripcion;
    }

    public function setDescripcion(string $Descripción): static
    {
        $this->Descripcion = $Descripción;

        return $this;
    }

    public function getOrigen(): ?string
    {
        return $this->Origen;
    }

    public function setOrigen(string $Origen): static
    {
        $this->Origen = $Origen;

        return $this;
    }

    public function getIdiomas(): ?string
    {
        return $this->Idiomas;
    }

    public function setIdiomas(?string $Idiomas): static
    {
        $this->Idiomas = $Idiomas;

        return $this;
    }

    public function getObjetosIniciales(): ?string
    {
        return $this->ObjetosIniciales;
    }

    public function setObjetosIniciales(?string $ObjetosIniciales): static
    {
        $this->ObjetosIniciales = $ObjetosIniciales;

        return $this;
    }

    public function getCompetencias(): ?string
    {
        return $this->Competencias;
    }

    public function setCompetencias(?string $Competencias): static
    {
        $this->Competencias = $Competencias;

        return $this;
    }

    public function isValidado(): ?bool
    {
        return $this->Validado;
    }

    public function setValidado(bool $Validado): static
    {
        $this->Validado = $Validado;

        return $this;
    }

    public function getAutor(): ?string
    {
        return $this->Autor;
    }

    public function setAutor(string $Autor): static
    {
        $this->Autor = $Autor;

        return $this;
    }

    public function getPlano(): ?string
    {
        return $this->Plano;
    }

    public function setPlano(string $Plano): static
    {
        $this->Plano = $Plano;

        return $this;
    }

    public function getImg(): ?string
    {
        return $this->img;
    }

    public function setImg(string $img): static
    {
        $this->img = $img;

        return $this;
    }
}

templates/revisiones/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello BuscadorController!{% endblock %}

{% block body %}
<div class="indices">
    <h1>Accesos Rápidos</h1>
    <a href="{{ path("app_revisiones_clase") }}">
        <span><i class="icofont-shield"></i> Clases</span> ({{clases}})
    </a>
    
    <a href="{{ path("app_revisiones_subclase") }}">
        <span><i class="icofont-duotone icofont-shield"></i> Subclases</span> ({{subclases}})
    </a>
    
    <a href="{{ path("app_revisiones_raza") }}">
        <span><i class="icofont-users-alt-3"></i> Razas</span> ({{razas}})
    </a>
    
     <a href="{{ path("app_revisiones_subraza") }}">
        <span><i class="icofont-user"></i> Subrazas</span> ({{subrazas}})
    </a>
    
    <a href="{{ path("app_revisiones_trasfondo") }}">
        <span><i class="icofont-paper"></i> Trasfondos</span> ({{trasfondos}})
    </a>
    
     <a href="{{ path("app_revisiones_dote") }}">
        <span><i class="icofont-listine-dots"></i> Dotes</span> ({{dotes}})
    </a>
    
     <a href="{{ path("app_revisiones_hechizo") }}">
        <span><i class="icofont-duotone icofont-wand"></i> Hechizos</span> ({{hechizos}})
    </a>
    
</div>
{% endblock %}

templates/revisiones/revision_clase.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello BuscadorController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>
<div>
   <h1>{{clase.nombre}}</h1>
    <h2>{{clase.requisitos}}</h2>
    <h2>{{clase.competencias}}</h2>
    <h2>{{clase.salvaciones}}</h2>
    <h2>{{clase.habilidadesaelegir}}</h2>
    <h2>{{clase.puntosdegolpe}}</h2>
    <h2>{{clase.equipamiento}}</h2>
    <h2>{{clase.autor}}</h2>
    <img src="{{clase.img}}"></img>
    <a href="{{ path ("app_revisiones_clase")}}">Volver</a>
</div>

{% endblock %}

templates/revisiones/revision_dote.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello BuscadorController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>
<div>
   <h1>{{dote.nombre}}</h1>
    <h2>{{dote.descripcion}}</h2>
    <h2>{{dote.requisitos}}</h2>
    <h2>{{dote.beneficios}}</h2>
    <h2>{{dote.autor}}</h2>
    <a href="{{ path ("app_revisiones_dote")}}">Volver</a>
</div>

{% endblock %}

templates/revisiones/revision_raza.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello BuscadorController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>
<div>
   <h1>{{raza.nombre}}</h1>
    <h2>{{raza.descripcion}}</h2>
    <h2>{{raza.fuerza}}</h2>
    <h2>{{raza.destreza}}</h2>
    <h2>{{raza.constitucion}}</h2>
    <h2>{{raza.inteligencia}}</h2>
    <h2>{{raza.sabiduria}}</h2>
    <h2>{{raza.carisma}}</h2>
    <h2>{{raza.velocidad}}</h2>
    <h2>{{raza.ataquedesarmado}}</h2>
    <h2>{{raza.autor}}</h2>
    <a href="{{ path ("app_revisiones_raza")}}">Volver</a>
</div>

{% endblock %}

templates/revisiones/revision_subclase.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello BuscadorController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>
<div>
   <h1>{{subclase.nombre}}</h1>
    <h2>{{subclase.requisitos}}</h2>
    <h2>{{subclase.autor}}</h2>
    <a href="{{ path ("app_revisiones_subclase")}}">Volver</a>
</div>

{% endblock %}

templates/revisiones/revision_subraza.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello BuscadorController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>
<div>
   <h1>{{subraza.nombre}}</h1>
    <h2>{{subraza.descripcion}}</h2>
    <h2>{{subraza.fuerza}}</h2>
    <h2>{{subraza.destreza}}</h2>
    <h2>{{subraza.constitucion}}</h2>
    <h2>{{subraza.inteligencia}}</h2>
    <h2>{{subraza.sabiduria}}</h2>
    <h2>{{subraza.carisma}}</h2>
    <h2>{{subraza.ataquedesarmado}}</h2>
    <h2>{{subraza.autor}}</h2>
    <a href="{{ path ("app_revisiones_subraza")}}">Volver</a>
</div>

{% endblock %}

templates/revisiones/revision_trasfondo.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello BuscadorController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>
<div>
   <h1>{{trasfondo.nombre}}</h1>
    <h2>{{trasfondo.descripcion}}</h2>
    <h2>{{trasfondo.idiomas}}</h2>
    <h2>{{trasfondo.objetosiniciales}}</h2>
    <h2>{{trasfondo.competencias}}</h2>
    <h2>{{trasfondo.plano}}</h2>
    <h2>{{trasfondo.autor}}</h2>
    <a href="{{ path ("app_revisiones_trasfondo")}}">Volver</a>
</div>

{% endblock %}

templates/revisiones/revisiones_clase.html.twig
{% extends 'base.html.twig' %}

{% block body %}


<div class="lista_revisiones">
    <h1>Revisiones de las Clases</h1>
    {% for revision in revisiones %}
    <div class="elemento_revisiones">
        <img src="{{revision.img}}">
        <h2>{{ revision.Nombre }}</h2>
        <div>
            <button onclick="location.href='{{ path("app_comprobar_clase", {'id': revision.id}) }}'" class="btn btn-info">Ver más</button>
            <button onclick="location.href='{{ path('app_validar_clase', {'id': revision.id}) }}'" class="btn btn-success">Validar clase</button>
            <button onclick="location.href='{{ path('app_eliminar_clase', {'id': revision.id}) }}'" class="btn btn-danger">Eliminar clase</button>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

templates/revisiones/revisiones_dote.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<div class="lista_revisiones">
    <h1>Revisiones de las Dotes</h1>
    {% for revision in revisiones %}
    <div class="elemento_revisiones">
        <img src="{{revision.img}}">
        <h2>{{ revision.Nombre }}</h2>
        <div>
            <button onclick="location.href='{{ path("app_comprobar_dote", {'id': revision.id}) }}'" class="btn btn-info">Ver más</button>
            <button onclick="location.href='{{ path('app_validar_dote', {'id': revision.id}) }}'" class="btn btn-success">Validar dote</button>
            <button onclick="location.href='{{ path('app_eliminar_dote', {'id': revision.id}) }}'" class="btn btn-danger">Eliminar dote</button>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

templates/revisiones/revisiones_hechizo.html.twig
{% extends 'base.html.twig' %}

{% block body %}


<div class="lista_revisiones">
    <h1>Revisiones de los Hechizos</h1>
    {% for revision in revisiones %}
    <div class="elemento_revisiones">
        <img src="{{revision.img}}">
        <h2>{{ revision.Nombre }}</h2>
        <div>
            <button onclick="location.href='{{ path("app_comprobar_hechizo", {'id': revision.id}) }}'" class="btn btn-info">Ver más</button>
            <button onclick="location.href='{{ path('app_validar_hechizo', {'id': revision.id}) }}'" class="btn btn-success">Validar hechizo</button>
            <button onclick="location.href='{{ path('app_eliminar_hechizo', {'id': revision.id}) }}'" class="btn btn-danger">Eliminar hechizo</button>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

templates/revisiones/revisiones_raza.html.twig
{% extends 'base.html.twig' %}

{% block body %}


<div class="lista_revisiones">
    <h1>Revisiones de las Razas</h1>
    {% for revision in revisiones %}
    <div class="elemento_revisiones">
        <img src="{{revision.img}}">
        <h2>{{ revision.Nombre }}</h2>
        <div>
            <button onclick="location.href='{{ path("app_comprobar_raza", {'id': revision.id}) }}'" class="btn btn-info">Ver más</button>
            <button onclick="location.href='{{ path('app_validar_raza', {'id': revision.id}) }}'" class="btn btn-success">Validar raza</button>
            <button onclick="location.href='{{ path('app_eliminar_raza', {'id': revision.id}) }}'" class="btn btn-danger">Eliminar raza</button>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

templates/revisiones/revisiones_subclase.html.twig
{% extends 'base.html.twig' %}

{% block body %}


<div class="lista_revisiones">
    <h1>Revisiones de las Subclases</h1>
    {% for revision in revisiones %}
    <div class="elemento_revisiones">
        <img src="{{revision.img}}">
        <h2>{{ revision.Nombre }}</h2>
        <div>
            <button onclick="location.href='{{ path("app_comprobar_subclase", {'id': revision.id}) }}'" class="btn btn-info">Ver más</button>
            <button onclick="location.href='{{ path('app_validar_subclase', {'id': revision.id}) }}'" class="btn btn-success">Validar subclase</button>
            <button onclick="location.href='{{ path('app_eliminar_subclase', {'id': revision.id}) }}'" class="btn btn-danger">Eliminar subclase</button>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

templates/revisiones/revisiones_subraza.html.twig
{% extends 'base.html.twig' %}

{% block body %}


<div class="lista_revisiones">
    <h1>Revisiones de las Subrazas</h1>
    {% for revision in revisiones %}
    <div class="elemento_revisiones">
        <img src="{{revision.img}}">
        <h2>{{ revision.Nombre }}</h2>
        <div>
            <button onclick="location.href='{{ path("app_comprobar_subraza", {'id': revision.id}) }}'" class="btn btn-info">Ver más</button>
            <button onclick="location.href='{{ path('app_validar_subraza', {'id': revision.id}) }}'" class="btn btn-success">Validar subraza</button>
            <button onclick="location.href='{{ path('app_eliminar_subraza', {'id': revision.id}) }}'" class="btn btn-danger">Eliminar subraza</button>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

templates/revisiones/revisiones_trasfondo.html.twig
{% extends 'base.html.twig' %}

{% block body %}


<div class="lista_revisiones">
    <h1>Revisiones de las Trasfondos</h1>
    {% for revision in revisiones %}
    <div class="elemento_revisiones">
        <img src="{{revision.img}}">
        <h2>{{ revision.Nombre }}</h2>
        <div>
            <button onclick="location.href='{{ path("app_comprobar_trasfondo", {'id': revision.id}) }}'" class="btn btn-info">Ver más</button>
            <button onclick="location.href='{{ path('app_validar_trasfondo', {'id': revision.id}) }}'" class="btn btn-success">Validar trasfondo</button>
            <button onclick="location.href='{{ path('app_eliminar_trasfondo', {'id': revision.id}) }}'" class="btn btn-danger">Eliminar trasfondo</button>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}